security:
    encoders:
        ihate\CoreBundle\Entity\User:
                          algorithm:           sha512
                          encode_as_base64:    true
                          iterations:          76

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        login_provider:
            entity: { class: ihate\CoreBundle\Entity\User, property: email }


    firewalls:
        dev:
            pattern:    ^/(_profiler|_wdt|css|js)
            security:   false
        secured_area:
            provider: login_provider
            pattern:  ^/
            form_login:
                always_use_default_target_path: true
                check_path: login_check
                login_path: login
            logout:
                path: logout
                target: login
            anonymous: ~

    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/login_check, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/, roles: ROLE_USER }
