parameters:
#    ihate_core.example.class: ihate\CoreBundle\Example

services:
#    ihate_core.example:
#        class: %ihate_core.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
