<?php

namespace ihate\CoreBundle\Repository;

use Doctrine\ORM\EntityRepository;
use ihate\CoreBundle\Entity\User;
use ihate\CoreBundle\Entity\Post;

/**
 * FollowRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentRepository extends EntityRepository
{

}
