<?php

namespace ihate\CoreBundle\Repository;

use Doctrine\ORM\EntityRepository;
use ihate\CoreBundle\Entity\Hate;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HateRepository extends EntityRepository
{
    private function getHatesIds($hates)
    {
        $ids = array();
        foreach ($hates as $hate) {
            $ids[] = $hate->getId();
        }
        return $ids;
    }
}
