<?php

namespace ihate\CoreBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * HateRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HateRepository extends EntityRepository
{

}
