<?php

namespace ihate\CoreBundle\Repository;

use Doctrine\ORM\EntityRepository;
use ihate\CoreBundle\Entity\User;
use ihate\CoreBundle\Entity\Post;

/**
 * PostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostRepository extends EntityRepository
{
    public function showPosts(User $user)
    {
        $ids = $this->getFollowersIds($user->getFollowers());
        return $this->createQueryBuilder('p')
            ->addSelect('u')
            ->join('p.user', 'u')
            ->where('p.user IN (:follow)')
            ->orWhere('p.user = :user')
            ->setParameter('user', $user)
            ->setParameter('follow', $ids)
            ->orderBy('p.createdAt', 'DESC')
            ->getQuery()
            ->getResult();
    }

    private function getFollowersIds($users)
    {
        $ids = array();
        foreach ($users as $user) {
            $ids[] = $user->getId();
        }
        return $ids;
    }

    public function showMyPosts(User $user)
    {
        return $this->createQueryBuilder('p')
            ->where('p.user = :user')
            ->setParameter('user', $user)
            ->orderBy('p.createdAt', 'DESC')
            ->getQuery()
            ->getResult();
    }
}
