<?php

namespace ihate\CoreBundle\Repository;

use Doctrine\ORM\EntityRepository;
use ihate\CoreBundle\Entity\User;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{
    /**
     * @param $needle
     * @return array
     */
    public function search($needle)
    {
        return $this->createQueryBuilder('u')
            ->where('u.name LIKE :needle')
            ->setParameter('needle', '%'.$needle.'%')
            ->getQuery()
            ->getResult();
    }
}
