<?php

namespace ihate\CoreBundle\Repository;

use Doctrine\ORM\EntityRepository;
use ihate\CoreBundle\Entity\User;
use Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{
    /**
     * @param $needle
     * @param \ihate\CoreBundle\Entity\User $user
     * @return array
     */
    public function search($needle, User $user)
    {
        return $this->createQueryBuilder('u')
            ->where('u.name LIKE :needle')
            ->andWhere('u.id != :id')
            ->setParameters(array(
                'needle' => '%'.$needle.'%',
                'id' => $user->getId(),
            ))
            ->getQuery()
            ->getResult();
    }

    /**
     * @return array
     */
    public function getUserTop(User $user)
    {
        $country = $user->getCountry();
        $results = $this->createQueryBuilder('u')
            ->addSelect('COUNT(h) AS hates')
            ->join('u.hates', 'h')
            ->leftjoin('h.user','hu')
            ->where('hu.country = :country')
            ->setParameter('country', $country)
            ->groupBy('u')
            ->orderBy('hates', 'DESC')
            ->addOrderBy('u.createdAt', 'DESC')
            ->getQuery()
            ->setMaxResults(5)
            ->getResult();
        $users = array();
        foreach ($results as $user) {
            $users[] = $user[0];
        }

        return $users;
    }
}
